/**
 * aggregate.test.ts
 *
 * Parity gate for the shared aggregation/span logic. Each case was produced by
 * the Python reference (inference_utils.aggregate_token_predictions_to_words +
 * word_labels_to_spans) over a real BioBERT tokenization, with hand-crafted
 * per-token labels chosen to exercise: a single-word entity, multi-subword
 * B-priority aggregation across consecutive entity words, an intra-word polarity
 * CONFLICT, and an 'I-' label with no preceding 'B-'. The TS port must reproduce
 * word labels, word offsets, and spans exactly.
 */

import {
  aggregateTokenPredictionsToWords,
  wordLabelsToSpans,
  type Span,
} from '../aggregate';

type RefCase = {
  text: string;
  wordIds: number[]; // -1 for special tokens
  offsets: [number, number][];
  predTokenLabels: string[];
  wordLabels: string[];
  wordOffsets: [number, number][];
  spans: Span[];
};

// Generated by mobile_app/model_prep (Python reference). See file docstring.
const CASES: RefCase[] = [
  {
    text: 'Patient denies Fever.',
    wordIds: [-1, 0, 1, 2, 3, -1],
    offsets: [[0, 0], [0, 7], [8, 14], [15, 20], [20, 21], [0, 0]],
    predTokenLabels: ['O', 'O', 'O', 'B-SYMPTOM_NEG', 'O', 'O'],
    wordLabels: ['O', 'O', 'B-SYMPTOM_NEG', 'O'],
    wordOffsets: [[0, 7], [8, 14], [15, 20], [20, 21]],
    spans: [
      { start: 0, end: 7, text: 'Patient', label: 'O' },
      { start: 8, end: 14, text: 'denies', label: 'O' },
      { start: 15, end: 20, text: 'Fever', label: 'SYMPTOM_NEG' },
      { start: 20, end: 21, text: '.', label: 'O' },
    ],
  },
  {
    text: 'On direct questioning she endorses maculopapular rash.',
    wordIds: [-1, 0, 1, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, -1],
    offsets: [[0, 0], [0, 2], [3, 9], [10, 21], [22, 25], [26, 29], [29, 33], [33, 34], [35, 38], [38, 41], [41, 43], [43, 45], [45, 48], [49, 50], [50, 53], [53, 54], [0, 0]],
    predTokenLabels: ['O', 'O', 'O', 'O', 'O', 'B-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'B-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'O', 'O', 'O', 'O'],
    wordLabels: ['O', 'O', 'O', 'O', 'B-SYMPTOM_POS', 'B-SYMPTOM_POS', 'O', 'O'],
    wordOffsets: [[0, 2], [3, 9], [10, 21], [22, 25], [26, 34], [35, 48], [49, 53], [53, 54]],
    spans: [
      { start: 0, end: 2, text: 'On', label: 'O' },
      { start: 3, end: 9, text: 'direct', label: 'O' },
      { start: 10, end: 21, text: 'questioning', label: 'O' },
      { start: 22, end: 25, text: 'she', label: 'O' },
      { start: 26, end: 34, text: 'endorses', label: 'SYMPTOM_POS' },
      { start: 35, end: 48, text: 'maculopapular', label: 'SYMPTOM_POS' },
      { start: 49, end: 53, text: 'rash', label: 'O' },
      { start: 53, end: 54, text: '.', label: 'O' },
    ],
  },
  {
    text: 'On direct questioning she endorses maculopapular rash.',
    wordIds: [-1, 0, 1, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, -1],
    offsets: [[0, 0], [0, 2], [3, 9], [10, 21], [22, 25], [26, 29], [29, 33], [33, 34], [35, 38], [38, 41], [41, 43], [43, 45], [45, 48], [49, 50], [50, 53], [53, 54], [0, 0]],
    predTokenLabels: ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-SYMPTOM_POS', 'I-SYMPTOM_NEG', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
    wordLabels: ['O', 'O', 'O', 'O', 'O', 'CONFLICT-B-SYMPTOM_POS-I-SYMPTOM_NEG-O-O-O', 'O', 'O'],
    wordOffsets: [[0, 2], [3, 9], [10, 21], [22, 25], [26, 34], [35, 48], [49, 53], [53, 54]],
    spans: [
      { start: 0, end: 2, text: 'On', label: 'O' },
      { start: 3, end: 9, text: 'direct', label: 'O' },
      { start: 10, end: 21, text: 'questioning', label: 'O' },
      { start: 22, end: 25, text: 'she', label: 'O' },
      { start: 26, end: 34, text: 'endorses', label: 'O' },
      { start: 35, end: 48, text: 'maculopapular', label: 'CONFLICT-B-SYMPTOM_POS-I-SYMPTOM_NEG-O-O-O' },
      { start: 49, end: 53, text: 'rash', label: 'O' },
      { start: 53, end: 54, text: '.', label: 'O' },
    ],
  },
  {
    text: 'On direct questioning she endorses maculopapular rash.',
    wordIds: [-1, 0, 1, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, -1],
    offsets: [[0, 0], [0, 2], [3, 9], [10, 21], [22, 25], [26, 29], [29, 33], [33, 34], [35, 38], [38, 41], [41, 43], [43, 45], [45, 48], [49, 50], [50, 53], [53, 54], [0, 0]],
    predTokenLabels: ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'I-SYMPTOM_POS', 'O', 'O', 'O'],
    wordLabels: ['O', 'O', 'O', 'O', 'O', 'O', 'I-SYMPTOM_POS', 'O'],
    wordOffsets: [[0, 2], [3, 9], [10, 21], [22, 25], [26, 34], [35, 48], [49, 53], [53, 54]],
    spans: [
      { start: 0, end: 2, text: 'On', label: 'O' },
      { start: 3, end: 9, text: 'direct', label: 'O' },
      { start: 10, end: 21, text: 'questioning', label: 'O' },
      { start: 22, end: 25, text: 'she', label: 'O' },
      { start: 26, end: 34, text: 'endorses', label: 'O' },
      { start: 35, end: 48, text: 'maculopapular', label: 'O' },
      { start: 49, end: 53, text: 'rash', label: 'SYMPTOM_POS' },
      { start: 53, end: 54, text: '.', label: 'O' },
    ],
  },
  {
    // Multi-word entity: two adjacent words both aggregate to I-SYMPTOM_POS, so
    // word_labels_to_spans starts at the first and EXTENDS through the second,
    // producing a single span covering "endorses maculopapular".
    text: 'On direct questioning she endorses maculopapular rash.',
    wordIds: [-1, 0, 1, 2, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, -1],
    offsets: [[0, 0], [0, 2], [3, 9], [10, 21], [22, 25], [26, 29], [29, 33], [33, 34], [35, 38], [38, 41], [41, 43], [43, 45], [45, 48], [49, 50], [50, 53], [53, 54], [0, 0]],
    predTokenLabels: ['O', 'O', 'O', 'O', 'O', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'O', 'O', 'O', 'O'],
    wordLabels: ['O', 'O', 'O', 'O', 'I-SYMPTOM_POS', 'I-SYMPTOM_POS', 'O', 'O'],
    wordOffsets: [[0, 2], [3, 9], [10, 21], [22, 25], [26, 34], [35, 48], [49, 53], [53, 54]],
    spans: [
      { start: 0, end: 2, text: 'On', label: 'O' },
      { start: 3, end: 9, text: 'direct', label: 'O' },
      { start: 10, end: 21, text: 'questioning', label: 'O' },
      { start: 22, end: 25, text: 'she', label: 'O' },
      { start: 26, end: 48, text: 'endorses maculopapular', label: 'SYMPTOM_POS' },
      { start: 49, end: 53, text: 'rash', label: 'O' },
      { start: 53, end: 54, text: '.', label: 'O' },
    ],
  },
];

describe('aggregation + span logic parity with Python reference', () => {
  for (let i = 0; i < CASES.length; i++) {
    const c = CASES[i];
    const wordIds = c.wordIds.map(w => (w === -1 ? null : w));

    it(`case ${i}: word labels + offsets match`, () => {
      const { wordLabels, wordOffsets } = aggregateTokenPredictionsToWords(
        c.text,
        wordIds,
        c.offsets,
        c.predTokenLabels,
      );
      expect(wordLabels).toEqual(c.wordLabels);
      expect(wordOffsets).toEqual(c.wordOffsets);
    });

    it(`case ${i}: spans match`, () => {
      const spans = wordLabelsToSpans(c.text, c.wordOffsets, c.wordLabels);
      expect(spans).toEqual(c.spans);
    });
  }
});
